
package com.kubris.soapClient.data;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Person", targetNamespace = "http://soapservice.demo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Person {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.kubris.soapClient.data.ZodiacSignResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSign", targetNamespace = "http://soapservice.demo.com/", className = "com.kubris.soapClient.data.GetSign")
    @ResponseWrapper(localName = "getSignResponse", targetNamespace = "http://soapservice.demo.com/", className = "com.kubris.soapClient.data.GetSignResponse")
    public ZodiacSignResponse getSign(
        @WebParam(name = "arg0", targetNamespace = "")
        PersonInput arg0);

}
